# https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/
apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-cloud-k8s-config
  labels:
    app: spring-cloud-k8s-config
    group: spring-cloud-k8s-samples
data:
  application.properties: |-
    poolsize.name=kube-pool
    poolsize.core=1
    poolsize.max=16